project_id = "gejsmlbctvwrvxtjvctz"

[functions.handle-vapi-webhook]
verify_jwt = false

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false
